CC=sparc-cross-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 

OBJ					= bin/sparc
EXECUTABLE 			= bin/squeeze2alexa-sparc
EXECUTABLE_STATIC	= bin/squeeze2alexa-sparc-static

include Makefile

