CC	 	= aarch64-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 
# for LD debug -s

OBJ					= bin/aarch64
EXECUTABLE 			= bin/squeeze2alexa-aarch64
EXECUTABLE_STATIC 	= bin/squeeze2alexa-aarch64-static

include Makefile

